# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Calendar-Generate
version:      0.7_01
version_from: lib/Calendar/Generate.pm
installdirs:  site
requires:
    Date::Calc:                    5.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
